# Generated by Django 5.0 on 2024-05-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='free_spaces',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='occupied_spaces',
        ),
    ]
