# Generated by Django 5.0 on 2024-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_parking_free_spaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='parking_space_status',
            field=models.BooleanField(),
        ),
    ]
